<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root>
	<Interpreter Version="2">
		<Project>
			<ScriptCount type="key">0</ScriptCount>
		</Project>
	</Interpreter>
	<ProjectExperiment>
		<viewflags>
			<Name type="key">Project_motiontest0829.CDP</Name>
			<ViewFlags type="key">1</ViewFlags>
			<item>
				<Name type="key">Project_motiontest0829</Name>
				<ViewFlags type="key">1</ViewFlags>
				<item>
					<Name type="key">Specifications</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Project Plans</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Models</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">Communication Matrices</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
				<item>
					<Name type="key">CustomFunctions</Name>
					<ViewFlags type="key">1</ViewFlags>
				</item>
			</item>
			<item>
				<Name type="key">Application_0829_1.CDL</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">Application_motiontest0829_2.CDL</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">Application_gptest0830.CDL</Name>
				<ViewFlags type="key">1</ViewFlags>
			</item>
			<item>
				<Name type="key">Application_gp2test0830_2.CDL</Name>
				<ViewFlags type="key">45</ViewFlags>
			</item>
		</viewflags>
	</ProjectExperiment>
</Root>